services:
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "127.0.0.1:16686:16686"
      - "127.0.0.1:14268:14268"

  app_a:
    build:
      context: .
      target: app_a
    ports:
      - "127.0.0.1:8091:8091"
    environment:
      JAEGER_ENDPOINT: "http://jaeger:14268/api/traces"

  app_b:
    build:
      context: .
      target: app_b
    ports:
      - "127.0.0.1:8092:8092"
    environment:
      JAEGER_ENDPOINT: "http://jaeger:14268/api/traces"
